// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMM7HFBdkw-7D4QF7B7QD4Cr_ESxRXxX0',
    appId: '1:1024937959426:web:c4c17e095dc0cb95f0071b',
    messagingSenderId: '1024937959426',
    projectId: 'wandeldagboek2025',
    authDomain: 'wandeldagboek2025.firebaseapp.com',
    storageBucket: 'wandeldagboek2025.firebasestorage.app',
    measurementId: 'G-GZS4V37YEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzKf8InPMlERNI-bFswzIFJCG-oXOhi9k',
    appId: '1:1024937959426:android:99c51098daa8b5f6f0071b',
    messagingSenderId: '1024937959426',
    projectId: 'wandeldagboek2025',
    storageBucket: 'wandeldagboek2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqLaMQ7O7KDijekfcbaonpaMfa7gEghOg',
    appId: '1:1024937959426:ios:810ff7a6a267ecf5f0071b',
    messagingSenderId: '1024937959426',
    projectId: 'wandeldagboek2025',
    storageBucket: 'wandeldagboek2025.firebasestorage.app',
    iosBundleId: 'nl.wandeldagboek.wandeldagboek2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqLaMQ7O7KDijekfcbaonpaMfa7gEghOg',
    appId: '1:1024937959426:ios:920438da7171448cf0071b',
    messagingSenderId: '1024937959426',
    projectId: 'wandeldagboek2025',
    storageBucket: 'wandeldagboek2025.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMM7HFBdkw-7D4QF7B7QD4Cr_ESxRXxX0',
    appId: '1:1024937959426:web:5ed20d23a3976400f0071b',
    messagingSenderId: '1024937959426',
    projectId: 'wandeldagboek2025',
    authDomain: 'wandeldagboek2025.firebaseapp.com',
    storageBucket: 'wandeldagboek2025.firebasestorage.app',
    measurementId: 'G-62WQK09LKS',
  );
}
